// Generated by fructose_gen.py

#include "ex6.h"

#include <stdlib.h>

int main(int argc, char* argv[])
{
    int retval = EXIT_SUCCESS;

    {
        simpletest simpletest_instance;
        simpletest_instance.add_test("floating", &simpletest::floating);
        const int r = simpletest_instance.run(argc, argv);
        retval = (retval == EXIT_SUCCESS) ? r : EXIT_FAILURE;
    }

    return retval;
}
